export const en = {
  "brand": "ssak",
  "tagline": "Habits that fit your day.",
  "today": "Today",
  "journey": "My habits",
  "settings": "Settings",
  "hero": "What will you do today?",
  "heroSub": "On busy days, do the easier option you picked.",
  "todayLabel": "TODAY’S HABITS",
  "add": "New habit",
  "empty": "What would you like to start?",
  "emptySub": "Pick one thing you’d like to do more often.",
  "start": "Choose a habit",
  "sample": "See an example",
  "sampleLabel": "EXAMPLE",
  "sampleClear": "Start my own habit",
  "done": "I did it",
  "checkInQuestion": "What did you do today?",
  "checkInHint": "Tap what you did to record it.",
  "tiny": "I did the easier option",
  "completed": "Done for today.",
  "tinyCompleted": "That counts too.",
  "undo": "Undo",
  "details": "View habit",
  "minimumLabel": "ON A BUSY DAY",
  "cueLabel": "WHEN TO DO IT",
  "week": "Your record so far",
  "weekSub": "Every day you do something counts, even if you do less.",
  "intention": "Weekly plan",
  "days": "days",
  "total": "Days completed",
  "noRush": "Missed a day? You can start again.",
  "reviewTitle": "How’s it going?",
  "reviewSub": "If it’s been hard to keep up, try doing less.",
  "review": "Review my plan",
  "reviewDue": "Time to review your plan",
  "pageJourney": "My habits",
  "journeySub": "Your current habits and the ones you’ve stopped tracking.",
  "practicing": "TRACKING NOW",
  "graduated": "NO LONGER TRACKING",
  "archiveEmpty": "No habits here yet.",
  "archiveSub": "When you no longer need daily check-ins, stop tracking. Your history stays here.",
  "createTitle": "Make a plan",
  "createSub": "Decide when to do it and what you’ll do on busy days.",
  "editTitle": "Change my plan",
  "nameLabel": "What would you like to do?",
  "namePlaceholder": "Read for 10 minutes",
  "cueField": "What will you do this after?",
  "cuePlaceholder": "After my morning coffee",
  "minimumField": "What’s an easier option for busy days?",
  "minimumPlaceholder": "Read just one page",
  "frequency": "How many days a week?",
  "frequencyHint": "Pick a number that feels manageable. You can change it later.",
  "save": "Start this habit",
  "saveChanges": "Save changes",
  "cancel": "Cancel",
  "back": "Back",
  "choose": "Habit ideas",
  "reading": "Read for 10 minutes",
  "readingCue": "After my morning coffee",
  "readingMin": "Read one page",
  "walking": "Go for a 10-minute walk",
  "walkingCue": "After lunch",
  "walkingMin": "Step outside for 2 minutes",
  "writing": "Write in my journal",
  "writingCue": "After brushing my teeth",
  "writingMin": "Write one sentence",
  "reminder": "Reminder time",
  "reminderHint": "Optional. Use 24-hour time, like 09:00. Follows your device’s time zone.",
  "webReminder": "You can set reminders in the iOS or Android app.",
  "invalid": "Fill in the habit, when you’ll do it, and the easier option.",
  "invalidTime": "Use a time like 09:00 or leave it empty.",
  "permission": "Notifications are off. Enable them in your device settings, or save without a reminder.",
  "reflectTitle": "How’s this\nplan working?",
  "reflectSub": "Think about what felt easy and what got in the way.",
  "easy": "It’s going well",
  "easySub": "Keep the plan as it is.",
  "adjust": "I want to do less",
  "adjustSub": "Choose something easier for busy days.",
  "ready": "I don’t need to track this anymore",
  "readySub": "You can stop tracking and keep your history.",
  "note": "Notes",
  "notePlaceholder": "What helped? What made it harder?",
  "reflectSave": "Save review",
  "saved": "Review saved.",
  "graduate": "Stop tracking this habit",
  "graduateTitle": "Ready to stop\ntracking this habit?",
  "graduateSub": "This removes the habit from Today and turns off its reminders. Your history stays, and you can start tracking again anytime.",
  "graduateConfirm": "Stop tracking",
  "keep": "Keep tracking",
  "restart": "Start tracking again",
  "restartSub": "Your previous records will be kept.",
  "edit": "Edit plan",
  "delete": "Delete habit",
  "deleteTitle": "Delete this habit and its history?",
  "deleteSub": "This cannot be undone. To keep your history, stop tracking instead.",
  "confirmDelete": "Delete permanently",
  "notFound": "This habit is no longer here.",
  "history": "PAST REVIEWS",
  "historyEmpty": "No reviews yet.",
  "graduationNote": "You’ve stopped tracking this habit.",
  "settingsTitle": "Settings",
  "language": "Language",
  "privacy": "Stored on this device",
  "privacySub": "No account. No ads. Habit records are stored on this device. Optional purchases use your app store and RevenueCat.",
  "backup": "Back up my records",
  "backupSub": "Copy your habits and history so you can restore them later.",
  "export": "Copy backup",
  "restore": "Restore a backup",
  "backupPlaceholder": "Paste your Ssak backup here",
  "backupWarning": "Restoring replaces the habits on this device. Save a copy of your current records first.",
  "restoreConfirm": "Replace with this backup",
  "copied": "Backup copied. Keep it somewhere safe.",
  "restored": "Your backup has been restored.",
  "backupError": "This backup is invalid. Your current records were not changed.",
  "backupLimit": "This backup has more active habits than your current plan allows.",
  "clipboardError": "Could not access the clipboard. Try again in the mobile app.",
  "plusTitle": "Track up to 3 habits",
  "plusSub": "One habit is free. Get Plus if you’d like to track more at once.",
  "freeTitle": "Free",
  "freeText": "Track one habit at a time, review your plan, and keep past records. No time limit.",
  "plusName": "Ssak Plus",
  "plusText": "Up to 3 habits at once · backup and restore · one-time purchase",
  "plusCta": "Explore Ssak Plus",
  "lifetime": "Pay once. No subscription.",
  "billingUnavailable": "Purchases aren’t available in this version yet. You can still use the free features.",
  "buy": "Buy Ssak Plus",
  "restorePurchase": "Restore purchase",
  "purchaseError": "The purchase could not be completed. Please try again.",
  "purchased": "Ssak Plus is ready to use.",
  "nothingRestore": "No Ssak Plus purchase was found for this store account.",
  "legacy": "Your original 3 habit slots are yours to keep.",
  "plusActive": "Ssak Plus is active",
  "welcomeKicker": "A SIMPLE HABIT TRACKER",
  "welcomeTitle": "Start with\nwhat you can do.",
  "welcomeSub": "Pick a habit and an easier option for busy days. Change the plan as you go.",
  "welcome1": "Set an easier option for busy days",
  "welcome2": "Pick it back up after a day off",
  "welcome3": "Stop tracking when you no longer need it",
  "welcomeButton": "Get started",
  "welcomeFooter": "No account · No ads · Your pace",
  "loading": "Loading…",
  "recorded": "Recorded",
  "notRecorded": "Not recorded",
  "savedPlan": "Your plan is saved.",
  "close": "Close",
  "optional": "Optional",
  "allDone": "You’re done for today."
} as const;
export type Copy = { [K in keyof typeof en]: string };
export const ko: Copy = {
  "brand": "ssak",
  "tagline": "내 생활에 맞는 습관.",
  "today": "오늘",
  "journey": "내 습관",
  "settings": "설정",
  "hero": "오늘은 무엇을 해볼까요?",
  "heroSub": "바쁜 날에는 미리 정해둔 만큼만 해도 좋아요.",
  "todayLabel": "오늘 할 일",
  "add": "새 습관",
  "empty": "어떤 습관을 시작할까요?",
  "emptySub": "평소에 더 자주 하고 싶었던 일을 하나 골라보세요.",
  "start": "습관 정하기",
  "sample": "예시 보기",
  "sampleLabel": "예시",
  "sampleClear": "내 습관 시작하기",
  "done": "했어요",
  "checkInQuestion": "오늘은 얼마나 했나요?",
  "checkInHint": "기록할 행동을 눌러주세요.",
  "tiny": "정해둔 만큼만 했어요",
  "completed": "오늘 기록했어요.",
  "tinyCompleted": "이만큼도 기록했어요.",
  "undo": "기록 취소",
  "details": "습관 자세히",
  "minimumLabel": "바쁜 날에는 이만큼만",
  "cueLabel": "언제 할까요?",
  "week": "지금까지의 기록",
  "weekSub": "조금만 한 날도 기록에 남아요.",
  "intention": "이번 주 계획",
  "days": "일",
  "total": "실천한 날",
  "noRush": "하루 쉬었어도 다시 하면 돼요.",
  "reviewTitle": "해보니 어떤가요?",
  "reviewSub": "꾸준히 하기 어렵다면 할 일을 조금 줄여보세요.",
  "review": "계획 돌아보기",
  "reviewDue": "계획을 한번 돌아보세요",
  "pageJourney": "내 습관",
  "journeySub": "지금 하고 있는 습관과 기록을 마친 습관을 모았어요.",
  "practicing": "기록 중",
  "graduated": "기록을 마친 습관",
  "archiveEmpty": "아직 기록을 마친 습관이 없어요.",
  "archiveSub": "매일 체크하지 않아도 된다면 기록을 마쳐보세요. 그동안의 기록은 여기에 남아요.",
  "createTitle": "언제, 얼마나 해볼까요?",
  "createSub": "언제 할지, 바쁜 날에는 얼마나 할지 정해보세요.",
  "editTitle": "계획 바꾸기",
  "nameLabel": "어떤 일을 하고 싶나요?",
  "namePlaceholder": "책 10분 읽기",
  "cueField": "무엇을 한 뒤에 할까요?",
  "cuePlaceholder": "아침 커피를 마신 뒤",
  "minimumField": "바쁜 날에는 얼마나 할까요?",
  "minimumPlaceholder": "책 한 페이지만 읽기",
  "frequency": "일주일에 며칠 할까요?",
  "frequencyHint": "무리 없이 할 수 있는 횟수로 정해보세요. 나중에 바꿔도 돼요.",
  "save": "이 습관 시작하기",
  "saveChanges": "변경 저장",
  "cancel": "취소",
  "back": "뒤로",
  "choose": "습관 예시",
  "reading": "책 10분 읽기",
  "readingCue": "아침 커피를 마신 뒤",
  "readingMin": "책 한 페이지 읽기",
  "walking": "10분 산책하기",
  "walkingCue": "점심을 먹은 뒤",
  "walkingMin": "2분만 밖에 나가기",
  "writing": "일기 쓰기",
  "writingCue": "양치한 뒤",
  "writingMin": "한 문장 쓰기",
  "reminder": "알림 시간",
  "reminderHint": "원할 때만 설정하세요. 09:00처럼 입력하면 기기 시간에 맞춰 알려줘요.",
  "webReminder": "알림은 iOS·Android 앱에서 설정할 수 있어요.",
  "invalid": "할 일, 언제 할지, 바쁜 날에는 얼마나 할지 모두 적어주세요.",
  "invalidTime": "09:00처럼 입력하거나 비워두세요.",
  "permission": "알림이 꺼져 있어요. 기기 설정에서 허용하거나 알림 없이 저장해주세요.",
  "reflectTitle": "계획대로\n하기 괜찮았나요?",
  "reflectSub": "쉬웠던 점이나 어려웠던 점을 떠올려보세요.",
  "easy": "이대로 하면 좋겠어요",
  "easySub": "지금 계획을 그대로 이어가요.",
  "adjust": "할 일을 줄이고 싶어요",
  "adjustSub": "바쁜 날 할 일을 더 쉽게 바꿔봐요.",
  "ready": "이제 기록 없이도 할 수 있어요",
  "readySub": "기록을 마쳐도 이전 기록은 남아요.",
  "note": "메모",
  "notePlaceholder": "어떤 점이 좋았나요? 어떤 점이 어려웠나요?",
  "reflectSave": "돌아본 내용 저장",
  "saved": "저장했어요.",
  "graduate": "매일 기록 그만하기",
  "graduateTitle": "이 습관의 기록을\n마칠까요?",
  "graduateSub": "오늘 할 일에서 빠지고 알림이 꺼져요. 이전 기록은 남고, 원하면 다시 기록할 수 있어요.",
  "graduateConfirm": "기록 마치기",
  "keep": "계속 기록하기",
  "restart": "다시 기록하기",
  "restartSub": "이전 기록은 그대로 남아요.",
  "edit": "계획 바꾸기",
  "delete": "습관 삭제",
  "deleteTitle": "습관과 기록을 모두 삭제할까요?",
  "deleteSub": "삭제한 기록은 되돌릴 수 없어요. 기록을 남기고 싶다면 ‘매일 기록 그만하기’를 선택하세요.",
  "confirmDelete": "모두 삭제",
  "notFound": "이 습관을 찾을 수 없어요.",
  "history": "돌아본 기록",
  "historyEmpty": "아직 돌아본 기록이 없어요.",
  "graduationNote": "이 습관은 기록을 마쳤어요.",
  "settingsTitle": "설정",
  "language": "언어",
  "privacy": "기록은 이 기기에 저장돼요",
  "privacySub": "계정도 광고도 없어요. 습관 기록은 이 기기에 저장돼요. 선택 결제에는 앱 스토어와 RevenueCat을 사용해요.",
  "backup": "기록 백업",
  "backupSub": "습관과 기록을 복사해두면 나중에 복원할 수 있어요.",
  "export": "백업 복사",
  "restore": "백업 복원",
  "backupPlaceholder": "싹 백업 내용을 붙여넣으세요",
  "backupWarning": "복원하면 이 기기의 습관을 교체해요. 먼저 현재 기록의 사본을 보관해주세요.",
  "restoreConfirm": "이 백업으로 교체",
  "copied": "백업을 복사했어요. 안전한 곳에 보관해주세요.",
  "restored": "백업을 복원했어요.",
  "backupError": "올바른 백업이 아니에요. 현재 기록은 바뀌지 않았어요.",
  "backupLimit": "백업의 활성 습관 수가 현재 이용 범위를 넘어요.",
  "clipboardError": "클립보드에 접근하지 못했어요. 모바일 앱에서 다시 시도해주세요.",
  "plusTitle": "습관을 최대 3개까지",
  "plusSub": "습관 하나는 무료예요. 여러 습관을 함께 기록하고 싶다면 Plus를 이용해보세요.",
  "freeTitle": "무료",
  "freeText": "습관 하나를 기록하고, 계획을 바꾸고, 지난 기록을 볼 수 있어요. 기간 제한은 없어요.",
  "plusName": "Ssak Plus",
  "plusText": "습관 최대 3개 동시 기록 · 백업과 복원 · 한 번만 결제",
  "plusCta": "Ssak Plus 알아보기",
  "lifetime": "한 번 결제하면 계속 쓸 수 있어요. 구독료는 없어요.",
  "billingUnavailable": "아직 이 버전에서는 결제할 수 없어요. 무료 기능은 계속 쓸 수 있어요.",
  "buy": "Ssak Plus 구매하기",
  "restorePurchase": "구매 복원",
  "purchaseError": "결제를 완료하지 못했어요. 다시 시도해주세요.",
  "purchased": "이제 Ssak Plus를 쓸 수 있어요.",
  "nothingRestore": "이 스토어 계정에서 Ssak Plus 구매를 찾지 못했어요.",
  "legacy": "기존에 사용하던 습관 3개 자리는 계속 유지돼요.",
  "plusActive": "Ssak Plus 이용 중",
  "welcomeKicker": "부담 없이 시작하는 습관 기록",
  "welcomeTitle": "할 수 있는 만큼부터\n시작해요.",
  "welcomeSub": "하고 싶은 일과 바쁜 날 할 일을 정해보세요. 해보면서 바꿔도 돼요.",
  "welcome1": "바쁜 날 할 일도 미리 정해두기",
  "welcome2": "하루 쉬었어도 다시 시작하기",
  "welcome3": "익숙해지면 매일 기록은 그만해도 돼요",
  "welcomeButton": "시작하기",
  "welcomeFooter": "계정 없이 · 광고 없이 · 나의 속도로",
  "loading": "불러오는 중…",
  "recorded": "실천 기록 있음",
  "notRecorded": "실천 기록 없음",
  "savedPlan": "계획을 저장했어요.",
  "close": "닫기",
  "optional": "선택",
  "allDone": "오늘 할 일을 마쳤어요."
};
export const ja: Copy = {
  "brand": "ssak",
  "tagline": "無理なく続ける習慣づくり。",
  "today": "今日",
  "journey": "習慣一覧",
  "settings": "設定",
  "hero": "今日やること",
  "heroSub": "忙しい日は、少なめに決めた分だけでも。",
  "todayLabel": "今日の習慣",
  "add": "習慣を追加",
  "empty": "何から始めますか？",
  "emptySub": "普段から続けたいことを、ひとつ選んでみましょう。",
  "start": "習慣を選ぶ",
  "sample": "使い方の例を見る",
  "sampleLabel": "サンプル",
  "sampleClear": "自分の習慣を始める",
  "done": "できた",
  "checkInQuestion": "今日はどこまでできましたか？",
  "checkInHint": "できたことをタップして記録しましょう。",
  "tiny": "少なめに決めた分だけできた",
  "completed": "今日の分を記録しました。",
  "tinyCompleted": "少なめでも、記録に残ります。",
  "undo": "取り消す",
  "details": "習慣を見る",
  "minimumLabel": "忙しい日は、これだけ",
  "cueLabel": "やるタイミング",
  "week": "これまでの記録",
  "weekSub": "少しだけできた日も、記録に残ります。",
  "intention": "今週の目安",
  "days": "日",
  "total": "できた日数",
  "noRush": "休んだ日があっても、また始めれば大丈夫。",
  "reviewTitle": "続けてみて、どうですか？",
  "reviewSub": "続けるのが大変なら、やることを減らしてみましょう。",
  "review": "振り返る",
  "reviewDue": "そろそろ振り返ってみましょう",
  "pageJourney": "習慣一覧",
  "journeySub": "続けている習慣と、記録を終えた習慣を確認できます。",
  "practicing": "記録中",
  "graduated": "記録を終了した習慣",
  "archiveEmpty": "記録を終えた習慣はまだありません。",
  "archiveSub": "毎日のチェックが必要なくなったら、記録を終了できます。これまでの記録は残ります。",
  "createTitle": "いつ、どのくらいやりますか？",
  "createSub": "やるタイミングと、忙しい日でもできることを決めましょう。",
  "editTitle": "計画を変更",
  "nameLabel": "どんなことをしたいですか？",
  "namePlaceholder": "10分読書する",
  "cueField": "何をした後にやりますか？",
  "cuePlaceholder": "朝のコーヒーの後",
  "minimumField": "忙しい日は、どこまでやりますか？",
  "minimumPlaceholder": "本を1ページ読む",
  "frequency": "週に何日やりますか？",
  "frequencyHint": "無理なくできそうな日数で大丈夫。後から変更できます。",
  "save": "この習慣を始める",
  "saveChanges": "変更を保存",
  "cancel": "キャンセル",
  "back": "戻る",
  "choose": "習慣の例",
  "reading": "10分読書する",
  "readingCue": "朝のコーヒーの後",
  "readingMin": "本を1ページ読む",
  "walking": "10分散歩する",
  "walkingCue": "昼食の後",
  "walkingMin": "2分だけ外に出る",
  "writing": "日記を書く",
  "writingCue": "歯を磨いた後",
  "writingMin": "一文を書く",
  "reminder": "通知する時刻",
  "reminderHint": "任意です。09:00のように24時間表示で入力してください。端末の時刻に合わせて通知します。",
  "webReminder": "通知はiOS・Androidアプリで設定できます。",
  "invalid": "やること、タイミング、忙しい日にやることを入力してください。",
  "invalidTime": "09:00のように入力するか、空欄にしてください。",
  "permission": "通知がオフです。端末設定で許可するか、通知なしで保存してください。",
  "reflectTitle": "この計画で\n続けられますか？",
  "reflectSub": "やりやすかったことや、大変だったことを振り返ってみましょう。",
  "easy": "このまま続けられそう",
  "easySub": "今の計画で続けます。",
  "adjust": "やることを減らしたい",
  "adjustSub": "忙しい日にやることを、もっと簡単にします。",
  "ready": "もう記録しなくても続けられそう",
  "readySub": "記録を終了しても、これまでの記録は残ります。",
  "note": "メモ",
  "notePlaceholder": "何がよかったですか？何が大変でしたか？",
  "reflectSave": "振り返りを保存",
  "saved": "保存しました。",
  "graduate": "この習慣の記録を終了",
  "graduateTitle": "毎日の記録を\n終了しますか？",
  "graduateSub": "今日の一覧から外れ、通知が止まります。これまでの記録は残り、いつでも再開できます。",
  "graduateConfirm": "記録を終了",
  "keep": "記録を続ける",
  "restart": "記録を再開",
  "restartSub": "これまでの記録はそのまま残ります。",
  "edit": "計画を変更",
  "delete": "習慣を削除",
  "deleteTitle": "習慣と記録を削除しますか？",
  "deleteSub": "削除すると元に戻せません。履歴を残したい場合は「この習慣の記録を終了」を選んでください。",
  "confirmDelete": "完全に削除",
  "notFound": "この習慣は見つかりません。",
  "history": "振り返りの記録",
  "historyEmpty": "振り返りの記録はまだありません。",
  "graduationNote": "この習慣の記録は終了しています。",
  "settingsTitle": "設定",
  "language": "言語",
  "privacy": "記録はこの端末に保存",
  "privacySub": "アカウントも広告も不要。習慣の記録はこの端末に保存されます。任意の購入にはストアとRevenueCatを使用します。",
  "backup": "記録のバックアップ",
  "backupSub": "習慣や記録をコピーしておくと、後から復元できます。",
  "export": "バックアップをコピー",
  "restore": "バックアップを復元",
  "backupPlaceholder": "Ssakのバックアップを貼り付け",
  "backupWarning": "復元すると端末の習慣が置き換わります。先に現在の記録を保存してください。",
  "restoreConfirm": "このバックアップに置き換える",
  "copied": "コピーしました。安全な場所に保管してください。",
  "restored": "復元しました。",
  "backupError": "無効なバックアップです。現在の記録は変更されていません。",
  "backupLimit": "バックアップの習慣数が現在のプランの上限を超えています。",
  "clipboardError": "クリップボードにアクセスできません。モバイルアプリでお試しください。",
  "plusTitle": "最大3つの習慣を記録",
  "plusSub": "習慣ひとつは無料です。複数の習慣を同時に記録したいときはPlusをご利用ください。",
  "freeTitle": "無料",
  "freeText": "習慣ひとつの記録、計画の見直し、過去の記録の確認ができます。期限はありません。",
  "plusName": "Ssak Plus",
  "plusText": "同時に最大3つの習慣を記録・バックアップと復元・買い切り",
  "plusCta": "Ssak Plusについて",
  "lifetime": "一度の購入で使えます。月額料金はかかりません。",
  "billingUnavailable": "このバージョンではまだ購入できません。無料の機能はそのまま使えます。",
  "buy": "Ssak Plusを購入",
  "restorePurchase": "購入を復元",
  "purchaseError": "購入を完了できませんでした。もう一度お試しください。",
  "purchased": "Ssak Plusを使えるようになりました。",
  "nothingRestore": "このストアアカウントに購入が見つかりません。",
  "legacy": "以前からの習慣3枠は、そのまま使えます。",
  "plusActive": "Ssak Plusを利用中",
  "welcomeKicker": "シンプルな習慣記録アプリ",
  "welcomeTitle": "できることから\n始めよう。",
  "welcomeSub": "続けたいことと、忙しい日でもできることを決めましょう。やってみてから変えても大丈夫。",
  "welcome1": "忙しい日にやることも決めておく",
  "welcome2": "休んだ後も、また始められる",
  "welcome3": "慣れたら、毎日の記録をやめても大丈夫",
  "welcomeButton": "始める",
  "welcomeFooter": "登録不要 · 広告なし · 自分のペースで",
  "loading": "読み込み中…",
  "recorded": "記録あり",
  "notRecorded": "記録なし",
  "savedPlan": "計画を保存しました。",
  "close": "閉じる",
  "optional": "任意",
  "allDone": "今日の分は終わりました。"
};
export const zh: Copy = {
  "brand": "ssak",
  "tagline": "找到適合自己的習慣。",
  "today": "今天",
  "journey": "我的習慣",
  "settings": "設定",
  "hero": "今天要做什麼？",
  "heroSub": "忙的時候，做到事先設定的基本目標就好。",
  "todayLabel": "今天的習慣",
  "add": "新增習慣",
  "empty": "想開始什麼習慣？",
  "emptySub": "選一件平常想多做一點的事。",
  "start": "選一個習慣",
  "sample": "看看範例",
  "sampleLabel": "範例",
  "sampleClear": "開始自己的習慣",
  "done": "我做到了",
  "checkInQuestion": "今天做了多少？",
  "checkInHint": "點選完成的內容來記錄。",
  "tiny": "做到基本目標了",
  "completed": "已記錄今天的完成狀況。",
  "tinyCompleted": "做到基本目標，也算完成。",
  "undo": "取消完成",
  "details": "查看習慣",
  "minimumLabel": "忙碌時，做這一點就好",
  "cueLabel": "什麼時候做",
  "week": "到目前為止的紀錄",
  "weekSub": "做得少一點的日子，也會留下紀錄。",
  "intention": "本週計畫",
  "days": "天",
  "total": "完成天數",
  "noRush": "漏了一天也沒關係，再繼續就好。",
  "reviewTitle": "最近做得怎麼樣？",
  "reviewSub": "如果不容易持續，可以試著少做一點。",
  "review": "回顧一下",
  "reviewDue": "回顧一下最近的狀況吧",
  "pageJourney": "我的習慣",
  "journeySub": "查看正在追蹤和已停止追蹤的習慣。",
  "practicing": "追蹤中",
  "graduated": "已停止追蹤",
  "archiveEmpty": "還沒有停止追蹤的習慣。",
  "archiveSub": "不需要每天打卡時，可以停止追蹤。過去的紀錄都會保留在這裡。",
  "createTitle": "什麼時候做？要做多少？",
  "createSub": "先想好什麼時候做，再設定忙的時候也做得到的基本目標。",
  "editTitle": "修改計畫",
  "nameLabel": "你想做什麼？",
  "namePlaceholder": "看書 10 分鐘",
  "cueField": "做完什麼事之後開始？",
  "cuePlaceholder": "喝完早晨咖啡後",
  "minimumField": "忙的時候，至少做多少？",
  "minimumPlaceholder": "只讀一頁",
  "frequency": "一週想做幾天？",
  "frequencyHint": "選一個做得到的天數，之後都能調整。",
  "save": "開始這個習慣",
  "saveChanges": "儲存變更",
  "cancel": "取消",
  "back": "返回",
  "choose": "習慣範例",
  "reading": "看書 10 分鐘",
  "readingCue": "喝完早晨咖啡後",
  "readingMin": "讀一頁書",
  "walking": "散步 10 分鐘",
  "walkingCue": "吃完午餐後",
  "walkingMin": "出門走2分鐘",
  "writing": "寫日記",
  "writingCue": "刷牙後",
  "writingMin": "寫一句話",
  "reminder": "提醒時間",
  "reminderHint": "可不填。請用 24 小時制，例如 09:00。提醒時間會依照裝置的時區。",
  "webReminder": "可以在 iOS 或 Android App 設定提醒。",
  "invalid": "請填寫習慣、什麼時候做，以及忙的時候要做多少。",
  "invalidTime": "請輸入如09:00的時間，或留空。",
  "permission": "通知已關閉。請在裝置設定允許，或不設定提醒直接儲存。",
  "reflectTitle": "這樣做，\n還順利嗎？",
  "reflectSub": "想想哪些地方做得順，哪些地方比較難。",
  "easy": "這樣做很順利",
  "easySub": "照目前的計畫繼續。",
  "adjust": "想少做一點",
  "adjustSub": "把忙的時候要做的事改得更簡單。",
  "ready": "不用打卡也能繼續做了",
  "readySub": "停止追蹤後，過去的紀錄還是會保留。",
  "note": "備註",
  "notePlaceholder": "什麼有幫助？哪裡比較難？",
  "reflectSave": "儲存回顧",
  "saved": "已儲存。",
  "graduate": "停止追蹤這個習慣",
  "graduateTitle": "要停止追蹤\n這個習慣嗎？",
  "graduateSub": "這個習慣會從今天的清單移除，提醒也會關閉。過去的紀錄會保留，隨時都能重新開始追蹤。",
  "graduateConfirm": "停止追蹤",
  "keep": "繼續追蹤",
  "restart": "重新開始追蹤",
  "restartSub": "過去的紀錄都會保留。",
  "edit": "修改計畫",
  "delete": "刪除習慣",
  "deleteTitle": "要刪除習慣和所有記錄嗎？",
  "deleteSub": "刪除後無法復原。想保留紀錄的話，請選「停止追蹤這個習慣」。",
  "confirmDelete": "永久刪除",
  "notFound": "找不到這個習慣。",
  "history": "回顧紀錄",
  "historyEmpty": "還沒有回顧紀錄。",
  "graduationNote": "已停止追蹤這個習慣。",
  "settingsTitle": "設定",
  "language": "語言",
  "privacy": "紀錄儲存在這台裝置",
  "privacySub": "不需帳號、沒有廣告。習慣記錄保存在此裝置。選購功能使用商店與RevenueCat。",
  "backup": "備份紀錄",
  "backupSub": "先複製習慣和紀錄，之後就能從備份還原。",
  "export": "複製備份",
  "restore": "還原備份",
  "backupPlaceholder": "貼上Ssak備份內容",
  "backupWarning": "還原會取代這台裝置上的習慣。請先保存目前記錄的副本。",
  "restoreConfirm": "以此備份取代",
  "copied": "已複製備份。請妥善保存。",
  "restored": "已還原備份。",
  "backupError": "備份無效。目前記錄未變更。",
  "backupLimit": "備份中的進行中習慣超過目前方案上限。",
  "clipboardError": "無法存取剪貼簿。請在手機App重試。",
  "plusTitle": "同時追蹤\n最多 3 個習慣",
  "plusSub": "追蹤一個習慣不用付費。想同時記錄更多習慣，可以選擇 Plus。",
  "freeTitle": "免費",
  "freeText": "一次追蹤一個習慣，也能調整計畫、查看過去的紀錄。沒有使用期限。",
  "plusName": "Ssak Plus",
  "plusText": "同時追蹤最多 3 個習慣・備份與還原・一次付費",
  "plusCta": "認識Ssak Plus",
  "lifetime": "付費一次就能繼續使用，不用訂閱。",
  "billingUnavailable": "這個版本還不能購買，免費功能仍可使用。",
  "buy": "購買 Ssak Plus",
  "restorePurchase": "恢復購買",
  "purchaseError": "未能完成購買。請再試一次。",
  "purchased": "現在可以使用 Ssak Plus 了。",
  "nothingRestore": "此商店帳號找不到Ssak Plus購買記錄。",
  "legacy": "原本的3個習慣名額會為你保留。",
  "plusActive": "已啟用Ssak Plus",
  "welcomeKicker": "簡單好用的習慣紀錄",
  "welcomeTitle": "從做得到的事\n開始。",
  "welcomeSub": "選一個想養成的習慣，再設定忙的時候也做得到的基本目標。之後可以隨時調整。",
  "welcome1": "先設定忙的時候要做多少",
  "welcome2": "漏了一天，也能接著做",
  "welcome3": "養成習慣後，不用一直打卡",
  "welcomeButton": "開始設定",
  "welcomeFooter": "不需帳號 · 沒有廣告 · 自己的步調",
  "loading": "載入中⋯",
  "recorded": "已有記錄",
  "notRecorded": "尚無記錄",
  "savedPlan": "計畫已儲存。",
  "close": "關閉",
  "optional": "選填",
  "allDone": "今天的事做完了。"
};
export const copies = { en, ko, ja, 'zh-TW': zh };
export type Language = keyof typeof copies;
export const languages: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'ko', label: '한국어' },
  { code: 'ja', label: '日本語' },
  { code: 'zh-TW', label: '繁體中文' },
];
