import type { Language } from './copy';
export const categoryIds = ['body', 'mind', 'learn', 'space', 'people', 'rest'] as const;
export type Category = (typeof categoryIds)[number];
export interface HabitIdea {
  id: string;
  category: Category;
  icon: string;
  name: string;
  cue: string;
  minimum: string;
}
const ids = [
  'walk',
  'stretch',
  'water',
  'breathe',
  'journal',
  'gratitude',
  'read',
  'language',
  'practice',
  'tidy',
  'prepare',
  'money',
  'message',
  'listen',
  'thanks',
  'screen',
  'winddown',
  'pause',
];
const icons = [
  '🚶',
  '🧘',
  '💧',
  '🌬️',
  '✍️',
  '☀️',
  '📖',
  '💬',
  '🎹',
  '🧺',
  '🎒',
  '🪙',
  '💌',
  '👂',
  '🤝',
  '📵',
  '🌙',
  '🍵',
];
const rows: Record<Language, string[]> = {
  en: [
    'Go for a 10-minute walk|After lunch|Step outside for 2 minutes',
    'Stretch a little|After leaving my desk|Stretch my shoulders once',
    'Drink some water|After brushing my teeth|Take a few sips of water',
    'Take a calm breath|After sitting down|Take 3 slow breaths',
    'Write in my journal|After brushing my teeth|Write one sentence',
    'Notice something good|After dinner|Name one good moment',
    'Read for 10 minutes|After my morning coffee|Read one page',
    'Learn a new word|After breakfast|Review one word',
    'Practice something I enjoy|After getting home|Practice for 2 minutes',
    'Clear a little space|After dinner|Put away one item',
    'Prepare for tomorrow|After changing for bed|Put one thing in my bag',
    'Track my spending|After dinner|Write down one purchase',
    'Keep in touch|After lunch|Send one short hello',
    'Listen with attention|When we sit down to eat|Ask one question and listen',
    'Say thank you|After finishing work|Thank one person',
    'Take a screen break|After plugging in my phone|Leave my phone aside for 2 minutes',
    'Get ready for bed|After brushing my teeth at night|Dim the lights',
    'Take a break|After making tea|Sit quietly for one minute',
  ],
  ko: [
    '10분 산책하기|점심을 먹은 뒤|2분만 밖에 나가기',
    '가볍게 스트레칭하기|책상에서 일어난 뒤|어깨 한 번 늘려주기',
    '물 조금 마시기|양치한 뒤|물 몇 모금 마시기',
    '차분하게 숨 고르기|자리에 앉은 뒤|천천히 세 번 숨 쉬기',
    '일기 쓰기|양치한 뒤|한 문장 쓰기',
    '좋았던 순간 떠올리기|저녁을 먹은 뒤|좋았던 일 하나 떠올리기',
    '책 10분 읽기|아침 커피를 마신 뒤|책 한 페이지 읽기',
    '새로운 단어 익히기|아침을 먹은 뒤|단어 하나 복습하기',
    '좋아하는 것 연습하기|집에 돌아온 뒤|2분만 연습하기',
    '주변 조금 정리하기|저녁을 먹은 뒤|물건 하나 제자리에 두기',
    '내일 준비하기|잠옷으로 갈아입은 뒤|가방에 필요한 물건 하나 넣기',
    '쓴 돈 기록하기|저녁을 먹은 뒤|지출 하나 적기',
    '안부 연락하기|점심을 먹은 뒤|잘 지내는지 메시지 보내기',
    '집중해서 들어주기|함께 식탁에 앉았을 때|질문 하나 하고 끝까지 듣기',
    '고마움 전하기|일을 마친 뒤|한 사람에게 고맙다고 말하기',
    '화면에서 잠깐 벗어나기|휴대폰을 충전기에 꽂은 뒤|2분만 휴대폰 내려놓기',
    '잠들 준비하기|밤에 양치한 뒤|방 조명 낮추기',
    '잠깐 쉬기|차를 준비한 뒤|1분만 조용히 앉아 있기',
  ],
  ja: [
    '10分散歩する|昼食の後|2分だけ外に出る',
    '軽くストレッチする|机から離れた後|肩を一度伸ばす',
    '水を少し飲む|歯磨きの後|水を数口飲む',
    'ゆっくり呼吸する|席に座った後|ゆっくり3回呼吸する',
    '日記を書く|歯磨きの後|一文を書く',
    'よかったことを思い出す|夕食の後|よかったことをひとつ挙げる',
    '10分読書する|朝のコーヒーの後|本を1ページ読む',
    '新しい単語を覚える|朝食の後|単語をひとつ復習する',
    '好きなことを練習する|帰宅した後|2分だけ練習する',
    '身の回りを整える|夕食の後|物をひとつ片付ける',
    '明日の準備をする|パジャマに着替えた後|必要な物をひとつ鞄に入れる',
    '使ったお金を記録する|夕食の後|買ったものをひとつ書く',
    '友達に連絡する|昼食の後|短いメッセージを送る',
    '相手の話を聞く|一緒に食卓についた時|ひとつ質問して最後まで聞く',
    '感謝を伝える|仕事を終えた後|ひとりにありがとうを伝える',
    '画面から少し離れる|スマホを充電した後|2分だけスマホを置く',
    '眠る準備をする|夜の歯磨きの後|照明をひとつ暗くする',
    'ひと息つく|お茶を用意した後|1分だけ静かに座る',
  ],
  'zh-TW': [
    '散步 10 分鐘|吃完午餐後|出門走 2 分鐘',
    '輕輕伸展一下|離開書桌後|伸展一次肩膀',
    '喝一點水|刷牙後|喝幾口水',
    '慢慢呼吸|坐下之後|慢慢呼吸3次',
    '寫日記|刷牙後|寫一句話',
    '想想今天的好事|吃完晚餐後|想起一件開心的事',
    '看書 10 分鐘|喝完早晨咖啡後|看一頁書',
    '學一個新單字|吃完早餐後|複習一個單字',
    '練習喜歡的事|回家之後|練習2分鐘',
    '整理身邊的空間|吃完晚餐後|把一件物品歸位',
    '準備明天的東西|換上睡衣後|把一件需要的東西放進包包',
    '記帳|吃完晚餐後|記下一筆花費',
    '和朋友聯絡|吃完午餐後|傳一則訊息問候朋友',
    '專心聽對方說話|一起坐下吃飯時|問一個問題並聽完',
    '表達感謝|結束工作後|向一個人說謝謝',
    '暫時離開螢幕|插上手機充電器後|放下手機2分鐘',
    '準備入睡|晚上刷牙後|調暗一盞燈',
    '留點時間休息|泡好茶後|安靜坐1分鐘',
  ],
};
export const getHabitIdeas = (language: Language): HabitIdea[] =>
  rows[language].map((row, index) => {
    const [name, cue, minimum] = row.split('|');
    return {
      id: ids[index],
      category: categoryIds[Math.floor(index / 3)],
      icon: icons[index],
      name,
      cue,
      minimum,
    };
  });
export const discoveryCopy = {
  en: {
    title: 'What would you like\nto do more often?',
    sub: 'Choose an example or write your own. You can change the details next.',
    own: 'Create my own habit',
    ownHint: 'You can start without choosing an example.',
    all: 'A few ideas',
    more: 'See all 18 ideas',
    less: 'Show fewer ideas',
    change: 'Browse other ideas',
    plan: 'Make a plan',
    replace: 'Choosing another example replaces the name, timing and easier option you entered.',
    categories: [
      'Body & energy',
      'A calmer mind',
      'Learning',
      'Everyday life',
      'Connection',
      'Rest',
    ],
    scope:
      'Purchases restore within the same app store. iOS and Android purchases are separate. Habit data does not sync automatically.',
    unavailable: 'The store could not load the product. Check your connection and try again later.',
  },
  ko: {
    title: '어떤 습관을\n만들고 싶나요?',
    sub: '예시를 고르거나 직접 적어보세요. 다음 화면에서 나에게 맞게 바꿀 수 있어요.',
    own: '내 습관 직접 정하기',
    ownHint: '예시를 고르지 않고 바로 시작할 수 있어요.',
    all: '추천 예시',
    more: '예시 18개 모두 보기',
    less: '간단히 보기',
    change: '다른 예시 보기',
    plan: '계획 정하기',
    replace: '다른 예시를 고르면 지금 적은 이름, 할 시점, 바쁜 날 할 일이 바뀌어요.',
    categories: ['몸과 컨디션', '마음 돌보기', '배움과 취미', '생활 정리', '관계', '휴식'],
    scope:
      '구매는 같은 앱 스토어에서 복원할 수 있어요. iOS와 Android 구매는 별도이며, 습관 기록은 자동 동기화되지 않아요.',
    unavailable: '스토어 상품을 불러오지 못했어요. 연결을 확인하고 잠시 후 다시 시도해주세요.',
  },
  ja: {
    title: 'どんな習慣を\n身につけたいですか？',
    sub: '例から選んでも、自分で入力しても大丈夫。次の画面で内容を変更できます。',
    own: '自分の習慣を決める',
    ownHint: '例を選ばずに、そのまま入力できます。',
    all: 'おすすめ',
    more: '18の例をすべて見る',
    less: '表示を減らす',
    change: 'ほかの例を見る',
    plan: '計画を立てる',
    replace: '別の例を選ぶと、入力中の名前、タイミング、忙しい日にやることが置き換わります。',
    categories: ['健康', '気分転換', '学習・趣味', '暮らし', '人付き合い', '休憩'],
    scope:
      '購入は同じアプリストアで復元できます。iOSとAndroidの購入は別です。習慣の記録は自動同期されません。',
    unavailable: '商品を読み込めませんでした。接続を確認し、後でもう一度お試しください。',
  },
  'zh-TW': {
    title: '想養成\n什麼習慣？',
    sub: '選一個範例，或自己填寫。下一步都能依照需要修改。',
    own: '自己設定習慣',
    ownHint: '不用選範例，也可以直接開始設定。',
    all: '推薦範例',
    more: '查看全部 18 個範例',
    less: '顯示少一點',
    change: '看看其他範例',
    plan: '設定計畫',
    replace: '選其他範例會取代剛才填寫的名稱、開始時機和基本目標。',
    categories: ['健康', '心情', '學習與興趣', '生活整理', '人際關係', '休息'],
    scope: '購買可在同一個 App 商店還原。iOS 與 Android 需分別購買。習慣記錄不會自動同步。',
    unavailable: '無法載入商品。請檢查連線，稍後再試。',
  },
};
